# Cloud Build config for building and deploying both backend and frontend to Cloud Run
# Assumes the following structure:
# - flask_app/Dockerfile (backend)
# - frontend/Dockerfile (frontend)
#
# Set these variables to match your project and region
substitutions:
  _REGION: us-central1
  _PROJECT: remixer-ai
  _REPO: remixer-repo

steps:
# Build and push backend image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/flask-app:latest', '-f', 'flask_app/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/flask-app:latest' ]

# Deploy backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [ 'run', 'deploy', 'flask-app',
      '--image=$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/flask-app:latest',
      '--platform=managed',
      '--region=$_REGION',
      '--allow-unauthenticated',
      '--port=8080',
      '--max-instances=1',
      '--timeout=900',
      '--memory=1Gi',
      '--cpu=1',
      '--set-env-vars=PYTHONUNBUFFERED=1',
      '--add-cloudsql-instances=',
      '--ingress=all',
      '--min-instances=0',
      '--max-instances=1',
      '--no-cpu-throttling',
      '--service-account=',
      '--update-env-vars=GUNICORN_CMD_ARGS=--timeout=120',
      '--exec-health-check-path=/health',
      '--exec-health-check-interval=30s',
      '--exec-health-check-timeout=5s',
      '--exec-health-check-unhealthy-threshold=3',
      '--exec-health-check-healthy-threshold=1' ]

# Build and push frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/frontend:latest', '-f', 'frontend/Dockerfile', 'frontend' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/frontend:latest' ]

# Deploy frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [ 'run', 'deploy', 'frontend',
      '--image=$_REGION-docker.pkg.dev/$_PROJECT/$_REPO/frontend:latest',
      '--platform=managed',
      '--region=$_REGION',
      '--allow-unauthenticated',
      '--port=8080',
      '--max-instances=1',
      '--timeout=900',
      '--memory=512Mi',
      '--cpu=1',
      '--ingress=all',
      '--min-instances=0',
      '--max-instances=1',
      '--no-cpu-throttling',
      '--exec-health-check-path=/health',
      '--exec-health-check-interval=30s',
      '--exec-health-check-timeout=5s',
      '--exec-health-check-unhealthy-threshold=3',
      '--exec-health-check-healthy-threshold=1' ]

timeout: 1800s
