services:
  python-app:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    image: remixer-python-app
    container_name: remixer-python-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    networks:
      - remixnet

  static-frontend:
    build: ./static_site
    image: remixer-static-frontend
    container_name: remixer-static-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - remixnet
    depends_on:
      - python-app

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: remixer-react-frontend
    container_name: remixer-react-frontend
    restart: unless-stopped
    ports:
      - "3001:8080"
    networks:
      - remixnet
    depends_on:
      - python-app

networks:
  remixnet:
    driver: bridge
