services:
  flask-app:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    image: remixer-flask-app
    container_name: remixer-flask-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    networks:
      - remixnet

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: remixer-react-frontend
    container_name: remixer-react-frontend
    restart: unless-stopped
    ports:
      - "3001:8080"
    networks:
      - remixnet
    depends_on:
      - flask-app

networks:
  remixnet:
    driver: bridge
