version: '3.8'
services:
  python-app:
    build:
      context: ./flask_app
      target: final
    image: remixer-python-app
    container_name: remixer-python-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    networks:
      - remixnet

  static-frontend:
    build: ./static_site
    image: remixer-static-frontend
    container_name: remixer-static-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - remixnet
    depends_on:
      - python-app

networks:
  remixnet:
    driver: bridge
