version: '3.8'
services:
  flask-app:
    build:
      context: ./flask_app
      target: final
    image: flask-app
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    networks:
      - remixnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - remixnet
    depends_on:
      - flask-app

networks:
  remixnet:
    driver: bridge
