# GitHub Actions workflow for REMIXER-AI: build, test, and (optionally) deploy
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test Docker image
        run: |
          docker compose build --no-cache
          docker compose up --abort-on-container-exit --exit-code-from python-app
      - name: Cleanup
        run: |
          docker compose down -v --remove-orphans
